language: node_js
node_js:
  - 12
dist: trusty
cache: npm
git:
  submodules: false
# branches:
#   only:
#   - implementtravisci
install:
  - npm install
script:
  - npm run test
after_failure:
  - exit
